### PR TITLE
Change 1(e/]/)000001 to 10(e/]/)00000 for 2/3/7 space

### PR DESCRIPTION
**Pull request by 837951602**
The latter one is 2 bytes shorter

### CODE REVIEW

**Comment by fasttime** [comment]
Thanks, this looks very good!

Can you please also run a build so that other files are updated? This is how it goes:

* Install [Node.js](https://nodejs.org/) (any version) if you don't have it yet.
* Install gulp-cli: run `npm install -g gulp-cli` in the command line.
* Still in the command line, cd into JScrewIt's local folder.
* Run `npm run build`. This recreates the files `lib/jscrewit.js` and `lib/jscrewit.min.js` from the sources. It also runs the unit tests to check that everything is still working.
* If the previous command worked, run `gulp full`. This may take 5-15 minutes, so go for a coffee. In the end, this will update the file `output.txt` with the new character lengths, so you can see the effect of your change on different characters.
* When done, there should be 3 more changed files to commit.

Again, let me know if you need help.

**Comment by 837951602** [comment]
I'm going to sleep (I'm in GMT+8) ^_^ (can I directly change the jscrewit.js and jscrewit.min.js?)

**Comment by fasttime** [comment]
Ok, good night. Just try this tomorrow when you have the time, it will be even faster than editing the lib files manually. `output.txt` cannot be edited manually anyway.

**Comment by 837951602** [comment]
I generated the output.txt but £ appeared as 拢

**Comment by fasttime** [comment]
Excellent work! Thanks for taking the time to do this.

**Comment by fasttime** [comment]
"£" not showing up correctly is clearly an encoding detection issue, and would fixed itself if output.txt started with a BOM. Meanwhile, if you open the file with UTF-8 encoding you should be fine.

**Comment by 837951602** [comment]
£ fixed

**Comment by fasttime** [comment]
Merged: https://github.com/fasttime/JScrewIt/commit/f3012f316548401c5dfc5fd7989734381504e1d4, https://github.com/fasttime/JScrewIt/commit/a832a1e4231d07e976fa30ce1eec3f23dd9311e7.

**Pull request closed without merging**
