### PR TITLE
New Features about Number.prototype.toLocaleString() for IE11 in win7 and 8, a lot of related new definitions (reopened PR)

### PR DESCRIPTION
**Pull request by Clayblockunova**

### CODE REVIEW

**Comment by Clayblockunova** [comment]
what should I do now?

**Comment by Clayblockunova** [comment]
how do these DLL files work?

**Comment by Clayblockunova** [comment]
should I abandon this PR?

**Comment by fasttime** [comment]
Sorry for the delay. As I said, I'm not sure about these definitions because I cannot reproduce all of them. I assume that Internet Explorer is using system components for Unicode support. These components could have been updated multiple times during the lifetime of Windows 7 or Windows 8, so it's uncertain how these definitions classify with regard to the operating system. I'd need to test them on a fresh VM with no Windows updates, but currently, I have time to look at that.

**Comment by Clayblockunova** [comment]
so, how much features should we need for IE11 in win7 and 8?

**Comment by Clayblockunova** [comment]
should I split features by edition or by language?

**Comment by Clayblockunova** [comment]
have your work finished?

**Comment by Clayblockunova** [comment]
Sorry for closing this PR again.

**Pull request closed without merging**
